# Generated by Django 4.2.2 on 2023-06-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_arrival_status',
            field=models.CharField(default='old', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.CharField(default='Shirt', max_length=50),
        ),
    ]
